"""Fix foreign key for user request logs

Revision ID: 4719e112dfdd
Revises: 0efa8eb55a77
Create Date: 2024-08-01 14:28:25.610810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4719e112dfdd'
down_revision: Union[str, None] = '0efa8eb55a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_request_logs_user_id_fkey', 'user_request_logs', type_='foreignkey')
    op.create_foreign_key(None, 'user_request_logs', 'auth', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_request_logs', type_='foreignkey')
    op.create_foreign_key('user_request_logs_user_id_fkey', 'user_request_logs', 'auth', ['user_id'], ['id'])
    # ### end Alembic commands ###
