"""Fix foreign key for user request logs2

Revision ID: 47dffe2587d0
Revises: 4719e112dfdd
Create Date: 2024-08-01 14:28:51.054811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dffe2587d0'
down_revision: Union[str, None] = '4719e112dfdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
