"""add cascade delete to blocked_units

Revision ID: 5b365664f49a
Revises: 5d9bb1691793
Create Date: 2024-08-01 12:10:49.516638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b365664f49a'
down_revision: Union[str, None] = '5d9bb1691793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocked_units_passport_id_fkey', 'blocked_units', type_='foreignkey')
    op.create_foreign_key(None, 'blocked_units', 'passports', ['passport_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocked_units', type_='foreignkey')
    op.create_foreign_key('blocked_units_passport_id_fkey', 'blocked_units', 'passports', ['passport_id'], ['id'])
    # ### end Alembic commands ###
