"""delete cascade auth models

Revision ID: 5d9bb1691793
Revises: dd4d3373ecd8
Create Date: 2024-08-01 11:58:31.144037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9bb1691793'
down_revision: Union[str, None] = 'dd4d3373ecd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_user_id_fkey', 'auth', type_='foreignkey')
    op.create_foreign_key(None, 'auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.create_foreign_key('auth_user_id_fkey', 'auth', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
