"""add Company and BlockedUnits models

Revision ID: a841f05f701e
Revises: b634553d8775
Create Date: 2024-07-30 22:23:51.231295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a841f05f701e'
down_revision: Union[str, None] = 'b634553d8775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_seria', sa.String(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('old_passport_number', sa.String(), nullable=True),
    sa.Column('old_passport_seria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_passport_number'),
    sa.UniqueConstraint('old_passport_seria'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('passport_seria')
    )
    op.create_table('blocked_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fio', sa.String(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('date_add_to_list', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blocked_units')
    op.drop_table('passports')
    op.drop_table('company')
    # ### end Alembic commands ###
