"""add relation and foreign key to auth -> user

Revision ID: ce5d6f686ebe
Revises: 5b417140dc55
Create Date: 2024-07-31 12:02:40.220242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5d6f686ebe'
down_revision: Union[str, None] = '5b417140dc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.drop_column('auth', 'user_id')
    # ### end Alembic commands ###
