"""delete cascade to DB for users and user_permission table

Revision ID: dd4d3373ecd8
Revises: ce5d6f686ebe
Create Date: 2024-08-01 11:56:49.631405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4d3373ecd8'
down_revision: Union[str, None] = 'ce5d6f686ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_permissions_user_id_fkey', 'user_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_permissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.create_foreign_key('user_permissions_user_id_fkey', 'user_permissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
